Further clean ups and stability for benchmark build process
Former-commit-id: 873a739bd07ed9890b00d28fd073147d82055418
Former-commit-id: 87e46df62780035ef173426c37fb3bb49d62f2d2

diff --git a/benchmark/detect_compiler b/benchmark/detect_compiler
--- a/benchmark/detect_compiler
+++ b/benchmark/detect_compiler
@@ -53,4 +53,21 @@ else
 fi
 
 
-echo "$GCC $CLANG $ICC"
+if hash templight++ 2>/dev/null; then
+    TEMPLIGHT=icpc
+elif [ -d "home/roman/PROFILER_CPP/templight_binary/metashell/3rd/templight/build/bin/" ]; then
+    cd "/home/roman/PROFILER_CPP/templight_binary/metashell/3rd/templight/build/bin/"
+    GRUBB=$(ls | grep templight++)
+    if [ "$GRUBB" == "templight++" ]; then
+        TEMPLIGHT=/home/roman/PROFILER_CPP/templight_binary/metashell/3rd/templight/build/bin/$GRUBB
+    fi
+    cd $CUR
+else
+    if [ "$1" == "profile" ]; then
+        echo "$1 not installed. Aborting"
+        exit 1
+    fi
+fi
+
+
+echo "$GCC $CLANG $ICC $TEMPLIGHT"
